<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uaModelStorageClient" nsURI="http://et.tu-dresden.de/ifa/EMFModelStorage/UA/model/v0.1"
    nsPrefix="uamsc">
  <eClassifiers xsi:type="ecore:EClass" name="AgteleEMFUAConnector" eSuperTypes="../../de.tud.et.ifa.agtele.eclipse.commons.emf.storage/model/modelStorage.ecore#//importAdapter/Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="AgteleEMFUAImportAdapter" eSuperTypes="../../de.tud.et.ifa.agtele.eclipse.commons.emf.storage/model/modelStorage.ecore#//importAdapter/ImportAdapter"/>
</ecore:EPackage>
